/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Carros;
import dao.CarrosDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilh
 */
public class MenuListaCarros extends javax.swing.JFrame {
    
    private void preencheTabela(){
        CarrosDAO carrosDAO = new CarrosDAO();
        String modelo = txtModeloCarroLista.getText();
        List<Carros> listaCarros = carrosDAO.getCarros(modelo);
        
        DefaultTableModel tabelaCarros = (DefaultTableModel) tblListaCarros.getModel();
        //Limpar a tabela para preencher com os novos dados
        tabelaCarros.setNumRows(0);
        
        for(Carros c : listaCarros){
            Object[] obj = new Object[]{
                c.getId(),
                c.getMarca(),
                c.getModelo(),
                c.getCor(),
                c.getQuilometragem(),
                c.getValordia(),
                c.getValorkm()
            };
            tabelaCarros.addRow(obj);
        }
    }

    /**
     * Creates new form MenuListaCarros
     */
    public MenuListaCarros() {
        initComponents();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdCarro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCarros = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtModeloCarroLista = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        btnEntregar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnEntregar.setText("Entregar");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("ID do Carro:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de carros");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Carros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(472, 6, 136, 64);

        tblListaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Modelo", "Cor", "Quilometragem"
            }
        ));
        jScrollPane1.setViewportView(tblListaCarros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(15, 203, 1130, 520);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modelo do carro:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(33, 137, 275, 48);

        txtModeloCarroLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtModeloCarroLista.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtModeloCarroListaCaretUpdate(evt);
            }
        });
        getContentPane().add(txtModeloCarroLista);
        txtModeloCarroLista.setBounds(314, 140, 372, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun/5559852.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -4, 1200, 780);

        setSize(new java.awt.Dimension(1177, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void txtModeloCarroListaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtModeloCarroListaCaretUpdate
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtModeloCarroListaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuListaCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaCarros;
    private javax.swing.JTextField txtIdCarro;
    private javax.swing.JTextField txtModeloCarroLista;
    // End of variables declaration//GEN-END:variables
}
