/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Carros;
import dao.CarrosDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilh
 */
public class MenuCarros extends javax.swing.JFrame {

    /**
     * Creates new form MenuCarros
     */
    public MenuCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtKmCarro2 = new javax.swing.JTextField();
        txtMarcaCarro1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCarro = new javax.swing.JTextField();
        txtMarcaCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModeloCarro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorCarro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKmCarro = new javax.swing.JTextField();
        btnCarroExcluir = new javax.swing.JButton();
        btnCarroLista = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtValorDiaCarro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValorKmCarro = new javax.swing.JTextField();
        btnCarroCadastrar = new javax.swing.JButton();
        btnCarroEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtCarroPesquisar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCarroPesquisar = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Valor por dia:");

        txtKmCarro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmCarro2ActionPerformed(evt);
            }
        });

        txtMarcaCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaCarro1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Marca:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carros");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("LocaCar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("ID:");

        txtIdCarro.setEditable(false);
        txtIdCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCarroActionPerformed(evt);
            }
        });

        txtMarcaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaCarroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Marca:");

        txtModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloCarroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Modelo:");

        txtCorCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorCarroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Cor:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("Quilometragem:");

        txtKmCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmCarroActionPerformed(evt);
            }
        });

        btnCarroExcluir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroExcluir.setText("EXCLUIR");
        btnCarroExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroExcluirActionPerformed(evt);
            }
        });

        btnCarroLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroLista.setText("LISTA");
        btnCarroLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroListaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Valor por dia:");

        txtValorDiaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDiaCarroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Valor por Km:");

        txtValorKmCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorKmCarroActionPerformed(evt);
            }
        });

        btnCarroCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroCadastrar.setText("CADASTRAR");
        btnCarroCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroCadastrarActionPerformed(evt);
            }
        });

        btnCarroEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroEditar.setText("EDITAR");
        btnCarroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroEditarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        txtCarroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarroPesquisarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Pesquisar ID:");

        btnCarroPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroPesquisar.setText("PESQUISAR");
        btnCarroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValorDiaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCarroCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCarroEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCarroExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCarroLista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(204, 204, 204))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtCarroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnCarroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCarroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCarroPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdCarro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtMarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addComponent(txtCorCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(txtKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtValorDiaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addComponent(txtValorKmCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnCarroCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarroEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarroExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCarroActionPerformed

    private void txtMarcaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaCarroActionPerformed

    private void txtModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCarroActionPerformed

    private void txtCorCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorCarroActionPerformed

    private void txtKmCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmCarroActionPerformed

    private void btnCarroExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdCarro.getText());
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.excluir(id);
        
        txtIdCarro.setText("");
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorKmCarro.setText("");
        txtValorDiaCarro.setText("");
    }//GEN-LAST:event_btnCarroExcluirActionPerformed

    private void btnCarroListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroListaActionPerformed
        // TODO add your handling code here:
        MenuListaCarros menuListaCarros = new MenuListaCarros();
        menuListaCarros.setVisible(true);
    }//GEN-LAST:event_btnCarroListaActionPerformed

    private void txtValorDiaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDiaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDiaCarroActionPerformed

    private void txtKmCarro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmCarro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmCarro2ActionPerformed

    private void txtValorKmCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorKmCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKmCarroActionPerformed

    private void btnCarroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroCadastrarActionPerformed
        // TODO add your handling code here:
        String marca = txtMarcaCarro.getText();
        String modelo = txtModeloCarro.getText();
        String cor = txtCorCarro.getText();
        int quilometragem = Integer.parseInt(txtKmCarro.getText());
        int valordia = Integer.parseInt(txtValorKmCarro.getText());
        int valorkm = Integer.parseInt(txtValorDiaCarro.getText());
        boolean status = true;
        
        Carros carros = new Carros();
        carros.setMarca(marca);
        carros.setModelo(modelo);
        carros.setCor(cor);
        carros.setQuilometragem(quilometragem);
        carros.setValordia(valordia);
        carros.setValorkm(valorkm);
        carros.setStatus(status);
        
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.inserir(carros);
        
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorKmCarro.setText("");
        txtValorDiaCarro.setText("");
    }//GEN-LAST:event_btnCarroCadastrarActionPerformed

    private void btnCarroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroEditarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdCarro.getText());
        String marca = txtMarcaCarro.getText();
        String modelo = txtModeloCarro.getText();
        String cor = txtCorCarro.getText();
        int quilometragem = Integer.parseInt(txtKmCarro.getText());
        int valordia = Integer.parseInt(txtValorDiaCarro.getText());
        int valorkm = Integer.parseInt(txtValorKmCarro.getText());
        boolean status = true;
        
        Carros carros = new Carros();
        carros.setId(id);
        carros.setMarca(marca);
        carros.setModelo(modelo);
        carros.setCor(cor);
        carros.setQuilometragem(quilometragem);
        carros.setValordia(valordia);
        carros.setValorkm(valorkm);
        carros.setStatus(status);
        
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.editar(carros);
        
        txtIdCarro.setText("");
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorKmCarro.setText("");
        txtValorDiaCarro.setText("");
    }//GEN-LAST:event_btnCarroEditarActionPerformed

    private void txtMarcaCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaCarro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaCarro1ActionPerformed

    private void txtCarroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarroPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarroPesquisarActionPerformed

    private void btnCarroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroPesquisarActionPerformed
        // TODO add your handling code here:
        int idPesquisaCarro = Integer.parseInt(txtCarroPesquisar.getText());
        CarrosDAO carrosDAO = new CarrosDAO();
        Carros carros = carrosDAO.getCarros(idPesquisaCarro);
        if(carros == null){
            JOptionPane.showMessageDialog(this, "Carro não encontrado");
        }else{
            txtIdCarro.setText(Integer.toString(carros.getId()));
            txtMarcaCarro.setText(carros.getMarca());
            txtModeloCarro.setText(carros.getModelo());
            txtCorCarro.setText(carros.getCor());
            txtKmCarro.setText(Integer.toString(carros.getQuilometragem()));
            txtValorDiaCarro.setText(Integer.toString(carros.getValordia()));
            txtValorKmCarro.setText(Integer.toString(carros.getValorkm()));
        }
    }//GEN-LAST:event_btnCarroPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarroCadastrar;
    private javax.swing.JButton btnCarroEditar;
    private javax.swing.JButton btnCarroExcluir;
    private javax.swing.JButton btnCarroLista;
    private javax.swing.JButton btnCarroPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCarroPesquisar;
    private javax.swing.JTextField txtCorCarro;
    private javax.swing.JTextField txtIdCarro;
    private javax.swing.JTextField txtKmCarro;
    private javax.swing.JTextField txtKmCarro2;
    private javax.swing.JTextField txtMarcaCarro;
    private javax.swing.JTextField txtMarcaCarro1;
    private javax.swing.JTextField txtModeloCarro;
    private javax.swing.JTextField txtValorDiaCarro;
    private javax.swing.JTextField txtValorKmCarro;
    // End of variables declaration//GEN-END:variables
}
