/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Carros;
import dao.CarrosDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilh
 */
public class MenuCarros extends javax.swing.JFrame {

    /**
     * Creates new form MenuCarros
     */
    public MenuCarros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        txtKmCarro2 = new javax.swing.JTextField();
        txtMarcaCarro1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCarro = new javax.swing.JTextField();
        txtMarcaCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtModeloCarro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCorCarro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKmCarro = new javax.swing.JTextField();
        btnCarroExcluir = new javax.swing.JButton();
        btnCarroLista = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtValorDiaCarro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValorKmCarro = new javax.swing.JTextField();
        btnCarroCadastrar = new javax.swing.JButton();
        btnCarroEditar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtCarroPesquisar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnCarroPesquisar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Valor por dia:");

        txtKmCarro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmCarro2ActionPerformed(evt);
            }
        });

        txtMarcaCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaCarro1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Marca:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carros");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Carros");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(473, 0, 136, 64);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(221, 195, 43, 48);

        txtIdCarro.setEditable(false);
        txtIdCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCarro);
        txtIdCarro.setBounds(282, 208, 126, 35);

        txtMarcaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarcaCarro);
        txtMarcaCarro.setBounds(282, 256, 177, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(158, 243, 106, 48);

        txtModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtModeloCarro);
        txtModeloCarro.setBounds(282, 322, 177, 35);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Modelo:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(133, 309, 131, 48);

        txtCorCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorCarro);
        txtCorCarro.setBounds(282, 388, 177, 35);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Cor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 375, 64, 48);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel6.setText("Quilometragem:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 441, 258, 48);

        txtKmCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKmCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtKmCarro);
        txtKmCarro.setBounds(282, 454, 177, 35);

        btnCarroExcluir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_delete.png"))); // NOI18N
        btnCarroExcluir.setText("     EXCLUIR");
        btnCarroExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroExcluir);
        btnCarroExcluir.setBounds(742, 412, 190, 60);

        btnCarroLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_side_list.png"))); // NOI18N
        btnCarroLista.setText("         LISTA");
        btnCarroLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroLista);
        btnCarroLista.setBounds(742, 490, 190, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setText("Valor por dia:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 507, 214, 48);

        txtValorDiaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDiaCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorDiaCarro);
        txtValorDiaCarro.setBounds(282, 524, 177, 35);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setText("Valor por Km:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(46, 577, 218, 48);

        txtValorKmCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorKmCarroActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorKmCarro);
        txtValorKmCarro.setBounds(282, 590, 177, 35);

        btnCarroCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        btnCarroCadastrar.setText("CADASTRAR");
        btnCarroCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroCadastrar);
        btnCarroCadastrar.setBounds(742, 256, 190, 60);

        btnCarroEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_edit.png"))); // NOI18N
        btnCarroEditar.setText("      EDITAR");
        btnCarroEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroEditar);
        btnCarroEditar.setBounds(742, 334, 190, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 167, 1102, 10);

        txtCarroPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtCarroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarroPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(txtCarroPesquisar);
        txtCarroPesquisar.setBounds(478, 93, 109, 35);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Pesquisar ID:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(269, 82, 203, 48);

        btnCarroPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCarroPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_form_magnify.png"))); // NOI18N
        btnCarroPesquisar.setText("PESQUISAR");
        btnCarroPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarroPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarroPesquisar);
        btnCarroPesquisar.setBounds(657, 70, 170, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun/5559852.jpg"))); // NOI18N
        jLabel12.setText("jLabel5");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-3, -4, 1130, 800);

        setSize(new java.awt.Dimension(1130, 789));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdCarroActionPerformed

    private void txtMarcaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaCarroActionPerformed

    private void txtModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloCarroActionPerformed

    private void txtCorCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorCarroActionPerformed

    private void txtKmCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmCarroActionPerformed

    private void btnCarroExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroExcluirActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdCarro.getText());
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.excluir(id);
        
        txtIdCarro.setText("");
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorDiaCarro.setText("");
        txtValorKmCarro.setText("");
        
    }//GEN-LAST:event_btnCarroExcluirActionPerformed

    private void btnCarroListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroListaActionPerformed
        // TODO add your handling code here:
        MenuListaCarros menuListaCarros = new MenuListaCarros();
        menuListaCarros.setVisible(true);
    }//GEN-LAST:event_btnCarroListaActionPerformed

    private void txtValorDiaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDiaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDiaCarroActionPerformed

    private void txtKmCarro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKmCarro2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKmCarro2ActionPerformed

    private void txtValorKmCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorKmCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorKmCarroActionPerformed

    private void btnCarroCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroCadastrarActionPerformed
        // TODO add your handling code here:
        String marca = txtMarcaCarro.getText();
        String modelo = txtModeloCarro.getText();
        String cor = txtCorCarro.getText();
        int quilometragem = Integer.parseInt(txtKmCarro.getText());
        int valordia = Integer.parseInt(txtValorDiaCarro.getText());
        int valorkm = Integer.parseInt(txtValorKmCarro.getText());
        boolean status = true;
        
        Carros carros = new Carros();
        carros.setMarca(marca);
        carros.setModelo(modelo);
        carros.setCor(cor);
        carros.setQuilometragem(quilometragem);
        carros.setValordia(valordia);
        carros.setValorkm(valorkm);
        carros.setStatus(status);
        
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.inserir(carros);
        
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorKmCarro.setText("");
        txtValorDiaCarro.setText("");
    }//GEN-LAST:event_btnCarroCadastrarActionPerformed

    private void btnCarroEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroEditarActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txtIdCarro.getText());
        String marca = txtMarcaCarro.getText();
        String modelo = txtModeloCarro.getText();
        String cor = txtCorCarro.getText();
        int quilometragem = Integer.parseInt(txtKmCarro.getText());
        int valordia = Integer.parseInt(txtValorDiaCarro.getText());
        int valorkm = Integer.parseInt(txtValorKmCarro.getText());
        boolean status = true;
        
        Carros carros = new Carros();
        carros.setId(id);
        carros.setMarca(marca);
        carros.setModelo(modelo);
        carros.setCor(cor);
        carros.setQuilometragem(quilometragem);
        carros.setValordia(valordia);
        carros.setValorkm(valorkm);
        carros.setStatus(status);
        
        CarrosDAO carrosDAO = new CarrosDAO();
        carrosDAO.editar(carros);
        
        txtIdCarro.setText("");
        txtMarcaCarro.setText("");
        txtModeloCarro.setText("");
        txtCorCarro.setText("");
        txtKmCarro.setText("");
        txtValorKmCarro.setText("");
        txtValorDiaCarro.setText("");
    }//GEN-LAST:event_btnCarroEditarActionPerformed

    private void txtMarcaCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaCarro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaCarro1ActionPerformed

    private void txtCarroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarroPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarroPesquisarActionPerformed

    private void btnCarroPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarroPesquisarActionPerformed
        // TODO add your handling code here:
        int idPesquisaCarro = Integer.parseInt(txtCarroPesquisar.getText());
        CarrosDAO carrosDAO = new CarrosDAO();
        Carros carros = carrosDAO.getCarros(idPesquisaCarro);
        if(carros == null){
            JOptionPane.showMessageDialog(this, "Carro não encontrado");
        }else{
            txtIdCarro.setText(Integer.toString(carros.getId()));
            txtMarcaCarro.setText(carros.getMarca());
            txtModeloCarro.setText(carros.getModelo());
            txtCorCarro.setText(carros.getCor());
            txtKmCarro.setText(Integer.toString(carros.getQuilometragem()));
            txtValorDiaCarro.setText(Integer.toString(carros.getValordia()));
            txtValorKmCarro.setText(Integer.toString(carros.getValorkm()));
        }
    }//GEN-LAST:event_btnCarroPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarroCadastrar;
    private javax.swing.JButton btnCarroEditar;
    private javax.swing.JButton btnCarroExcluir;
    private javax.swing.JButton btnCarroLista;
    private javax.swing.JButton btnCarroPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCarroPesquisar;
    private javax.swing.JTextField txtCorCarro;
    private javax.swing.JTextField txtIdCarro;
    private javax.swing.JTextField txtKmCarro;
    private javax.swing.JTextField txtKmCarro2;
    private javax.swing.JTextField txtMarcaCarro;
    private javax.swing.JTextField txtMarcaCarro1;
    private javax.swing.JTextField txtModeloCarro;
    private javax.swing.JTextField txtValorDiaCarro;
    private javax.swing.JTextField txtValorKmCarro;
    // End of variables declaration//GEN-END:variables
}
