/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Alugados;
import beans.Carros;
import beans.Clientes;
import dao.AlugadosDAO;
import dao.CarrosDAO;
import dao.ClientesDAO;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author Guilh
 */
public class MenuAlugar extends javax.swing.JFrame {
    
    private void preencherComboCarros(){
        CarrosDAO carrosDAO = new CarrosDAO();
        List<Carros> lista = carrosDAO.getCarros("");
        
        for(Carros c: lista){
            cmbCarros.addItem(c);
        }
    }
    
    

    /**
     * Creates new form MenuAlugar
     */
    public MenuAlugar() {
        initComponents();
        preencherComboCarros();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        btnAlugar1 = new javax.swing.JButton();
        cmbCarros = new javax.swing.JComboBox();
        txtClientescpf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alugar");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("LocaCar");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(503, 6, 168, 64);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("CPF do Cliente:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 358, 240, 48);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Carro:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(151, 279, 95, 48);

        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_side_list.png"))); // NOI18N
        btnRelatorio.setText("RELATÓRIO");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio);
        btnRelatorio.setBounds(871, 355, 240, 54);

        btnAlugar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnAlugar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_key.png"))); // NOI18N
        btnAlugar1.setText("ALUGAR");
        btnAlugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlugar1);
        btnAlugar1.setBounds(871, 283, 240, 54);

        cmbCarros.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(cmbCarros);
        cmbCarros.setBounds(264, 279, 565, 48);

        txtClientescpf.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtClientescpf);
        txtClientescpf.setBounds(264, 355, 565, 54);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun/5559852.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -4, 1130, 740);

        setSize(new java.awt.Dimension(1137, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        new MenuRelatorioAlugados().setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnAlugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugar1ActionPerformed
        // TODO add your handling code here:
        LocalDate localDate = LocalDate.now();
        Date data = Date.valueOf(localDate);
        long clientescpf = Long.parseLong(txtClientescpf.getText());
        Carros carrosid = (Carros) cmbCarros.getSelectedItem();
        
        Alugados alugados = new Alugados();
        alugados.setClientescpf(clientescpf);
        alugados.setCarrosid(carrosid);
        alugados.setData(data);
        
        AlugadosDAO alugadosDAO = new AlugadosDAO();
        alugadosDAO.alugar(alugados);
        JOptionPane.showMessageDialog(this, "Carro alugado com sucesso!");
    }//GEN-LAST:event_btnAlugar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAlugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAlugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlugar1;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JComboBox cmbCarros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtClientescpf;
    // End of variables declaration//GEN-END:variables
}
