/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Clientes;
import dao.ClientesDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilh
 */
public class MenuListaClientes extends javax.swing.JFrame {
    
    private void preencheTabela(){
        ClientesDAO clientesDAO = new ClientesDAO();
        String nome = txtIdClienteLista.getText();
        List<Clientes> listaClientes = clientesDAO.getClientes(nome);
        
        DefaultTableModel tabelaClientes = (DefaultTableModel) tblListaClientes.getModel();
        //Limpar a tabela para preencher com os novos dados
        tabelaClientes.setNumRows(0);
        
        for(Clientes c : listaClientes){
            Object[] obj = new Object[]{
                c.getCpf(),
                c.getNome(),
            };
            tabelaClientes.addRow(obj);
        }
    }

    /**
     * Creates new form MenuListaClientes
     */
    public MenuListaClientes() {
        initComponents();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdClienteLista = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaClientes = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 6, 167, 64);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Nome do Cliente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(71, 137, 278, 48);

        txtIdClienteLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtIdClienteLista.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtIdClienteListaCaretUpdate(evt);
            }
        });
        getContentPane().add(txtIdClienteLista);
        txtIdClienteLista.setBounds(370, 140, 251, 45);

        tblListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "CPF", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tblListaClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(22, 197, 1207, 540);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun/5559852.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -4, 1280, 790);

        setSize(new java.awt.Dimension(1264, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdClienteListaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtIdClienteListaCaretUpdate
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_txtIdClienteListaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuListaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuListaClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaClientes;
    private javax.swing.JTextField txtIdClienteLista;
    // End of variables declaration//GEN-END:variables
}
