/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locacar;

import beans.Clientes;
import dao.ClientesDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Guilh
 */
public class MenuClientes extends javax.swing.JFrame {

    /**
     * Creates new form MenuClientes
     */
    public MenuClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClienteLista = new javax.swing.JButton();
        txtCpfCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnClienteCadastrar = new javax.swing.JButton();
        btnClienteEditar = new javax.swing.JButton();
        btnClienteExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        btnClientePesquisar = new javax.swing.JButton();
        txtClientePesquisar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(457, 6, 167, 64);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CPF:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(138, 372, 68, 48);

        btnClienteLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClienteLista.setForeground(new java.awt.Color(0, 0, 0));
        btnClienteLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_side_list.png"))); // NOI18N
        btnClienteLista.setText("         LISTA");
        btnClienteLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteLista);
        btnClienteLista.setBounds(615, 498, 190, 60);

        txtCpfCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCpfCliente);
        txtCpfCliente.setBounds(224, 385, 240, 35);

        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomeCliente);
        txtNomeCliente.setBounds(221, 445, 243, 35);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(103, 432, 106, 48);

        btnClienteCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClienteCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnClienteCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        btnClienteCadastrar.setText("CADASTRAR");
        btnClienteCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteCadastrar);
        btnClienteCadastrar.setBounds(615, 263, 190, 60);

        btnClienteEditar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClienteEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnClienteEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_edit.png"))); // NOI18N
        btnClienteEditar.setText("       EDITAR");
        btnClienteEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteEditar);
        btnClienteEditar.setBounds(615, 341, 190, 60);

        btnClienteExcluir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClienteExcluir.setForeground(new java.awt.Color(0, 0, 0));
        btnClienteExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_delete.png"))); // NOI18N
        btnClienteExcluir.setText("     EXCLUIR");
        btnClienteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteExcluir);
        btnClienteExcluir.setBounds(615, 419, 190, 60);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 235, 1114, 10);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Pesquisar CPF:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(62, 128, 228, 48);

        btnClientePesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClientePesquisar.setForeground(new java.awt.Color(0, 0, 0));
        btnClientePesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_form_magnify.png"))); // NOI18N
        btnClientePesquisar.setText("PESQUISAR");
        btnClientePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientePesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientePesquisar);
        btnClientePesquisar.setBounds(636, 128, 190, 60);

        txtClientePesquisar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtClientePesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientePesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(txtClientePesquisar);
        txtClientePesquisar.setBounds(308, 141, 277, 35);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroun/5559852.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-3, -4, 1140, 810);

        setSize(new java.awt.Dimension(1130, 778));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteListaActionPerformed
        // TODO add your handling code here:
        MenuListaClientes menuListaClientes = new MenuListaClientes();
        menuListaClientes.setVisible(true);
    }//GEN-LAST:event_btnClienteListaActionPerformed

    private void txtCpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfClienteActionPerformed

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void btnClienteCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteCadastrarActionPerformed
        // TODO add your handling code here:
        long cpf = Long.parseLong(txtCpfCliente.getText());
        String nome = txtNomeCliente.getText();
        
        Clientes clientes = new Clientes();
        clientes.setCpf(cpf);
        clientes.setNome(nome);
        
        ClientesDAO clientesDAO = new ClientesDAO();
        clientesDAO.inserir(clientes);
        
        txtCpfCliente.setText("");
        txtNomeCliente.setText("");

    }//GEN-LAST:event_btnClienteCadastrarActionPerformed

    private void btnClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteEditarActionPerformed
        // TODO add your handling code here:
        long cpf = Long.parseLong(txtCpfCliente.getText());
        String nome = txtNomeCliente.getText();
        
        Clientes clientes = new Clientes();
        clientes.setCpf(cpf);
        clientes.setNome(nome);
        
        ClientesDAO clientesDAO = new ClientesDAO();
        clientesDAO.editar(clientes);
        
        txtCpfCliente.setText("");
        txtNomeCliente.setText("");
    }//GEN-LAST:event_btnClienteEditarActionPerformed

    private void btnClienteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteExcluirActionPerformed
        // TODO add your handling code here:
        long cpf = Long.parseLong(txtCpfCliente.getText());
        ClientesDAO clientesDAO = new ClientesDAO();
        clientesDAO.excluir(cpf);
        
        txtCpfCliente.setText("");
        txtNomeCliente.setText("");
    }//GEN-LAST:event_btnClienteExcluirActionPerformed

    private void btnClientePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientePesquisarActionPerformed
        // TODO add your handling code here:
        long cpfClientePesquisar = Long.parseLong(txtClientePesquisar.getText());
        ClientesDAO clientesDAO = new ClientesDAO();
        Clientes clientes = clientesDAO.getClientes(cpfClientePesquisar);
        if(clientes == null){
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
        }else{
            txtCpfCliente.setText(Long.toString(clientes.getCpf()));
            txtNomeCliente.setText(clientes.getNome());
        }
    }//GEN-LAST:event_btnClientePesquisarActionPerformed

    private void txtClientePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientePesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientePesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteCadastrar;
    private javax.swing.JButton btnClienteEditar;
    private javax.swing.JButton btnClienteExcluir;
    private javax.swing.JButton btnClienteLista;
    private javax.swing.JButton btnClientePesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtClientePesquisar;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
